### ISSUE TITLE
Ambulance-controller issue

### ISSUE THREAD

**Issue by s21227c** [pjwstkIOprojekt/backend#30]
### Description

**In post method you can add ambulance with int type in string atribute**

**Comment by s20462** [comment]
not an issue
i.e. we try to create ambulance with plates 23232 as an Integer it is mapped to String "23232"
we the input is for example 22c controler returns 400 Bad Request
same with enums, an enum maps to integer i.e. we have enum value S and it maps let's say to 1 and we pass 1 as a Integer the result will be object with enum value S but when we pass 322 for example we get BadRequest because int with value 322 doesn't map to any enum value
